<?php

/*
+--------------------------------------------------------------------------
|   sqMail 1.0.1
|   ========================================
|   Integrated by Wang Jue
|   http://www.wjue.org
|   ========================================
|   Web: http://www.guanxiCRM.com
|   Email: wjue@wjue.org
|   Licence: GPL
+---------------------------------------------------------------------------
*/

$modversion['name'] = _MI_SQMQIL_NAME;
$modversion['version'] = 1.4;
$modversion['description'] = _MI_SQMAIL_DESC;
$modversion['author'] = 'Xoops integration by wjue<br>( http://www.wjue.org/ )';
$modversion['credits'] = 'SquirrelMail.org';
$modversion['help'] = '';
$modversion['license'] = 'GPL see LICENSE';
$modversion['official'] = 0;
$modversion['image'] = 'images/sq_logo.png';
$modversion['dirname'] = 'sqmail';

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
//$modversion['sqlfile']['mysql'] = "sql/mysql.sql";
//$modversion['sqlfile']['postgresql'] = "sql/pgsql.sql";

// Menu
$modversion['hasMain'] = 1;

// Templates
$modversion['templates'][1]['file'] = 'sqmail_index.html';
$modversion['templates'][1]['description'] = 'Smarty template file';
